MFiX-Exa: MFIXParticleContainer Class Reference
MFIXParticleContainer Class Reference final
#include <mfix_pc.H>
Public Types
using MFIXParIter = amrex::ParIter< AoSrealData::count, AoSintData::count, SoArealData::count, SoAintData::count >
using MFIXParConstIter = amrex::ParConstIter< AoSrealData::count, AoSintData::count, SoArealData::count, SoAintData::count >
Public Member Functions
int NumberOfParticles (MFIXParIter &pti)
void setTotalNumParticles (const int num_particles)
MFIXParticleContainer (amrex::AmrCore *amr_core, SolidsPhase &solids, Reactions &reactions)
virtual ~MFIXParticleContainer ()
void InitData ()
void InitParticlesAscii (const std::string &file)
void InitParticlesAuto ()
void InitParticlesRuntimeVariables (const int adv_enthalpy)
void RemoveOutOfRange (int lev, const amrex::EBFArrayBoxFactory *ebfactory, const amrex::MultiFab *ls_phi, int ls_refinement)
void Replicate (amrex::IntVect &Nrep, amrex::Geometry &geom, amrex::DistributionMapping &dmap, amrex::BoxArray &ba)
void printParticles ()
void AllocData ()
void PrintParticleCounts ()
amrex::Vector< std::map< std::pair< int, int >, amrex::NeighborList< ParticleType > > > get_neighbor_list ()
void EvolveParticles (int lev, int nstep, amrex::Real dt, amrex::Real time, amrex::RealVect &gravity, amrex::EBFArrayBoxFactory *ebfactory, const amrex::MultiFab *ls_phi, const int ls_refinement, amrex::MultiFab *cost, std::string &knapsack_weight_type, int &nsubsteps, const int advect_enthalpy, const amrex::Real enthalpy_source, const int update_mass, const int update_momentum, const int update_enthalpy)
void MFIX_PC_InitCollisionParams ()
void UpdateMaxVelocity ()
void UpdateMaxForces (std::map< PairIndex, amrex::Gpu::DeviceVector< amrex::Real >> &pfor, std::map< PairIndex, amrex::Gpu::DeviceVector< amrex::Real >> &wfor)
amrex::RealVect GetMaxVelocity ()
amrex::Vector< amrex::RealVect > GetMaxForces ()
void WriteAsciiFileForInit (const std::string &filename)
void output (int estatus, int finish, int nstep, amrex::Real dt, amrex::Real time)
void writeAllAtLevel (int lev=0)
void SolidsVolumeDeposition (int lev, amrex::MultiFab &mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
template<typename FB >
void SolidsVolumeDeposition (FB WeightFunc, int lev, amrex::MultiFab &mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
void InterphaseTxfrDeposition (int lev, amrex::MultiFab &mf_tmp_eps, amrex::MultiFab &txfr_mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags, const int advect_enthalpy)
template<typename F >
void InterphaseTxfrDeposition (F WeightFunc, int lev, amrex::MultiFab &mf_tmp_eps, amrex::MultiFab &txfr_mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags, const int advect_enthalpy)
void ComputeAverageVelocities (const int lev, const amrex::Real time, const std::string &basename, const amrex::Vector< amrex::Real > &avg_vel_p, const amrex::Vector< amrex::Real > &avg_region_x_w, const amrex::Vector< amrex::Real > &avg_region_x_e, const amrex::Vector< amrex::Real > &avg_region_y_s, const amrex::Vector< amrex::Real > &avg_region_y_n, const amrex::Vector< amrex::Real > &avg_region_z_b, const amrex::Vector< amrex::Real > &avg_region_z_t)
void ComputeAverageTemperatures (const int lev, const amrex::Real time, const std::string &basename, const amrex::Vector< amrex::Real > &avg_T_p, const amrex::Vector< amrex::Real > &avg_region_x_w, const amrex::Vector< amrex::Real > &avg_region_x_e, const amrex::Vector< amrex::Real > &avg_region_y_s, const amrex::Vector< amrex::Real > &avg_region_y_n, const amrex::Vector< amrex::Real > &avg_region_z_b, const amrex::Vector< amrex::Real > &avg_region_z_t)
void MFIX_PC_SolidsVelocityDeposition (int lev, amrex::Array< amrex::MultiFab *, 3 > &vel_s_mf, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
void PICHydroStep (int lev, const bool apply_forces, const bool update_parcels, const bool use_taylor_approx, const amrex::Real advance_vel_p, amrex::Real dt, amrex::RealVect &gravity, amrex::Vector< amrex::Array< amrex::MultiFab *, 3 > > &vel_s_in, amrex::MultiFab &ep_s_out, amrex::Array< amrex::MultiFab *, 3 > &vel_s_out, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags, amrex::EBFArrayBoxFactory *ebfactory, const int ls_refinement, const amrex::MultiFab *ls_phi)
void MFIX_PC_AdvanceParcels (amrex::Real dt, const int advect_enthalpy, const amrex::Real enthalpy_source, amrex::Vector< amrex::MultiFab * > &cost, std::string &knapsack_weight_type)
void setSortingBinSizes (amrex::IntVect sorting_bin)
void checkParticleBoxSize (int lev, amrex::IntVect &max_grid_size, amrex::Real frac_particle_bin)
void downsizeParticleBoxes (int lev, const amrex::IntVect &new_grid_size)
void resetCostByCount (int lev, amrex::Vector< amrex::MultiFab * > &cost)
void setMaxGridSize (const amrex::IntVect &rhs)
void setMaxGridSize (int size_x, int size_y, int size_z)
void setSortInt (int sort_particle_int)
const amrex::IntVect & MaxGridSize () const noexcept
amrex::Real particleImbalance ()
Public Attributes
const runtimeRealData m_runtimeRealData
Member Typedef Documentation
MFIXParConstIter
using MFIXParticleContainer::MFIXParConstIter = amrex::ParConstIter<AoSrealData::count,AoSintData::count, SoArealData::count,SoAintData::count>
MFIXParIter
using MFIXParticleContainer::MFIXParIter = amrex::ParIter<AoSrealData::count,AoSintData::count, SoArealData::count,SoAintData::count>
Constructor & Destructor Documentation
MFIXParticleContainer()
MFIXParticleContainer::MFIXParticleContainer (amrex::AmrCore * amr_core, SolidsPhase & solids, Reactions & reactions)
References runtimeRealData::count, and m_runtimeRealData.
~MFIXParticleContainer()
virtual MFIXParticleContainer::~MFIXParticleContainer () inline virtual
Member Function Documentation
AllocData()
void MFIXParticleContainer::AllocData ()
checkParticleBoxSize()
void MFIXParticleContainer::checkParticleBoxSize (int lev, amrex::IntVect & max_grid_size, amrex::Real frac_particle_bin)
ComputeAverageTemperatures()
void MFIXParticleContainer::ComputeAverageTemperatures (const int lev, const amrex::Real time, const std::string & basename, const amrex::Vector< amrex::Real > & avg_T_p, const amrex::Vector< amrex::Real > & avg_region_x_w, const amrex::Vector< amrex::Real > & avg_region_x_e, const amrex::Vector< amrex::Real > & avg_region_y_s, const amrex::Vector< amrex::Real > & avg_region_y_n, const amrex::Vector< amrex::Real > & avg_region_z_b, const amrex::Vector< amrex::Real > & avg_region_z_t)
References NumberOfParticles(), and SoArealData::temperature.
Referenced by mfix::WriteAverageRegions().
ComputeAverageVelocities()
void MFIXParticleContainer::ComputeAverageVelocities (const int lev, const amrex::Real time, const std::string & basename, const amrex::Vector< amrex::Real > & avg_vel_p, const amrex::Vector< amrex::Real > & avg_region_x_w, const amrex::Vector< amrex::Real > & avg_region_x_e, const amrex::Vector< amrex::Real > & avg_region_y_s, const amrex::Vector< amrex::Real > & avg_region_y_n, const amrex::Vector< amrex::Real > & avg_region_z_b, const amrex::Vector< amrex::Real > & avg_region_z_t)
References SoArealData::mass, NumberOfParticles(), SoArealData::velx, SoArealData::vely, and SoArealData::velz.
Referenced by mfix::WriteAverageRegions().
downsizeParticleBoxes()
void MFIXParticleContainer::downsizeParticleBoxes (int lev, const amrex::IntVect & new_grid_size)
EvolveParticles()
void MFIXParticleContainer::EvolveParticles (int lev, int nstep, amrex::Real dt, amrex::Real time, amrex::RealVect & gravity, amrex::EBFArrayBoxFactory * ebfactory, const amrex::MultiFab * ls_phi, const int ls_refinement, amrex::MultiFab * cost, std::string & knapsack_weight_type, int & nsubsteps, const int advect_enthalpy, const amrex::Real enthalpy_source, const int update_mass, const int update_momentum, const int update_enthalpy)
References cfrelvel(), SoArealData::convection, SoArealData::cp_s, cross_product(), SoArealData::density, dot_product(), SoArealData::dragx, SoArealData::dragy, SoArealData::dragz, GetMaxForces(), GetMaxVelocity(), runtimeRealData::h_s_txfr, interp_level_set(), level_set_normal(), m_runtimeRealData, SoArealData::mass, runtimeRealData::mass_sn_txfr, NumberOfParticles(), SoArealData::omegax, SoArealData::omegay, SoArealData::omegaz, SoArealData::oneOverI, SoAintData::phase, SoArealData::radius, SoAintData::state, SoArealData::temperature, UpdateMaxForces(), UpdateMaxVelocity(), runtimeRealData::vel_s_txfr, SoArealData::velx, SoArealData::vely, SoArealData::velz, SoArealData::volume, and runtimeRealData::X_sn.
get_neighbor_list()
amrex::Vector<std::map<std::pair<int, int>, amrex::NeighborList<ParticleType> > > MFIXParticleContainer::get_neighbor_list () inline
Referenced by mfix::PIC_to_DEM().
GetMaxForces()
Vector< RealVect > MFIXParticleContainer::GetMaxForces ()
Referenced by EvolveParticles().
GetMaxVelocity()
RealVect MFIXParticleContainer::GetMaxVelocity ()
Referenced by EvolveParticles().
InitData()
void MFIXParticleContainer::InitData ()
InitParticlesAscii()
void MFIXParticleContainer::InitParticlesAscii (const std::string & file)
References SoArealData::convection, AoSrealData::count, SoArealData::count, SoAintData::count, SoArealData::cp_s, SoArealData::density, SoArealData::dragcoeff, SoArealData::dragx, SoArealData::dragy, SoArealData::dragz, SoArealData::mass, SoArealData::omegax, SoArealData::omegay, SoArealData::omegaz, SoArealData::oneOverI, SoAintData::phase, SoArealData::radius, SoAintData::state, SoArealData::statwt, SoArealData::temperature, SoArealData::velx, SoArealData::vely, SoArealData::velz, and SoArealData::volume.
InitParticlesAuto()
void MFIXParticleContainer::InitParticlesAuto ()
References AoSrealData::count, SoArealData::count, ParticlesGenerator::generate(), and ParticlesGenerator::generate_prop().
InitParticlesRuntimeVariables()
void MFIXParticleContainer::InitParticlesRuntimeVariables (const int adv_enthalpy)
References SoArealData::cp_s.
InterphaseTxfrDeposition() [1/2]
template<typename F > void MFIXParticleContainer::InterphaseTxfrDeposition (F WeightFunc, int lev, amrex::MultiFab & mf_tmp_eps, amrex::MultiFab & txfr_mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags, const int advect_enthalpy)
InterphaseTxfrDeposition() [2/2]
void MFIXParticleContainer::InterphaseTxfrDeposition (int lev, amrex::MultiFab & mf_tmp_eps, amrex::MultiFab & txfr_mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags, const int advect_enthalpy)
Do the actual PIC deposition for CalcDragOnFluid
Referenced by mfix::mfix_calc_txfr_fluid().
MaxGridSize()
const amrex::IntVect& MFIXParticleContainer::MaxGridSize () const inline noexcept
MFIX_PC_AdvanceParcels()
void MFIXParticleContainer::MFIX_PC_AdvanceParcels (amrex::Real dt, const int advect_enthalpy, const amrex::Real enthalpy_source, amrex::Vector< amrex::MultiFab * > & cost, std::string & knapsack_weight_type)
MFIX_PC_InitCollisionParams()
void MFIXParticleContainer::MFIX_PC_InitCollisionParams ()
References SoArealData::density, SoAintData::phase, and SoArealData::radius.
MFIX_PC_SolidsVelocityDeposition()
void MFIXParticleContainer::MFIX_PC_SolidsVelocityDeposition (int lev, amrex::Array< amrex::MultiFab *, 3 > & vel_s_mf, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Deposit parcel velocity to the grid
NumberOfParticles()
int MFIXParticleContainer::NumberOfParticles (MFIXParIter & pti) inline
Referenced by ComputeAverageTemperatures(), ComputeAverageVelocities(), and EvolveParticles().
output()
void MFIXParticleContainer::output (int estatus, int finish, int nstep, amrex::Real dt, amrex::Real time)
Referenced by mfix::output().
particleImbalance()
Real MFIXParticleContainer::particleImbalance ()
PICHydroStep()
void MFIXParticleContainer::PICHydroStep (int lev, const bool apply_forces, const bool update_parcels, const bool use_taylor_approx, const amrex::Real advance_vel_p, amrex::Real dt, amrex::RealVect & gravity, amrex::Vector< amrex::Array< amrex::MultiFab *, 3 > > & vel_s_in, amrex::MultiFab & ep_s_out, amrex::Array< amrex::MultiFab *, 3 > & vel_s_out, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags, amrex::EBFArrayBoxFactory * ebfactory, const int ls_refinement, const amrex::MultiFab * ls_phi)
PrintParticleCounts()
void MFIXParticleContainer::PrintParticleCounts ()
printParticles()
void MFIXParticleContainer::printParticles ()
References SoArealData::count, SoAintData::phase, and SoAintData::state.
RemoveOutOfRange()
void MFIXParticleContainer::RemoveOutOfRange (int lev, const amrex::EBFArrayBoxFactory * ebfactory, const amrex::MultiFab * ls_phi, int ls_refinement)
References interp_level_set(), SoArealData::radius, and SoArealData::statwt.
Replicate()
void MFIXParticleContainer::Replicate (amrex::IntVect & Nrep, amrex::Geometry & geom, amrex::DistributionMapping & dmap, amrex::BoxArray & ba)
References SoArealData::convection, AoSrealData::count, SoArealData::count, SoArealData::cp_s, SoArealData::density, SoArealData::dragcoeff, SoArealData::dragx, SoArealData::dragy, SoArealData::dragz, SoArealData::mass, SoArealData::omegax, SoArealData::omegay, SoArealData::omegaz, SoArealData::oneOverI, SoAintData::phase, SoArealData::radius, SoAintData::state, SoArealData::statwt, SoArealData::temperature, SoArealData::velx, SoArealData::vely, SoArealData::velz, and SoArealData::volume.
resetCostByCount()
void MFIXParticleContainer::resetCostByCount (int lev, amrex::Vector< amrex::MultiFab * > & cost)
setMaxGridSize() [1/2]
void MFIXParticleContainer::setMaxGridSize (const amrex::IntVect & rhs) inline
setMaxGridSize() [2/2]
void MFIXParticleContainer::setMaxGridSize (int size_x, int size_y, int size_z) inline
setSortingBinSizes()
void MFIXParticleContainer::setSortingBinSizes (amrex::IntVect sorting_bin) inline
setSortInt()
void MFIXParticleContainer::setSortInt (int sort_particle_int) inline
setTotalNumParticles()
void MFIXParticleContainer::setTotalNumParticles (const int num_particles) inline
Referenced by mfix::PIC_to_DEM(), and mfix::PIC_to_PIC().
SolidsVolumeDeposition() [1/2]
template<typename FB > void MFIXParticleContainer::SolidsVolumeDeposition (FB WeightFunc, int lev, amrex::MultiFab & mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Do the actual PIC deposition for CalcVolumeFraction
SolidsVolumeDeposition() [2/2]
void MFIXParticleContainer::SolidsVolumeDeposition (int lev, amrex::MultiFab & mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Referenced by mfix::mfix_calc_volume_fraction().
UpdateMaxForces()
void MFIXParticleContainer::UpdateMaxForces (std::map< PairIndex, amrex::Gpu::DeviceVector< amrex::Real >> & pfor, std::map< PairIndex, amrex::Gpu::DeviceVector< amrex::Real >> & wfor)
Referenced by EvolveParticles().
UpdateMaxVelocity()
void MFIXParticleContainer::UpdateMaxVelocity ()
References SoArealData::velx, SoArealData::vely, and SoArealData::velz.
Referenced by EvolveParticles().
writeAllAtLevel()
void MFIXParticleContainer::writeAllAtLevel (int lev = 0)
Write out all particles at a level
WriteAsciiFileForInit()
void MFIXParticleContainer::WriteAsciiFileForInit (const std::string & filename)
Write out all particles in the format of the particle_input.dat files so we can initialize a run with them
References SoArealData::count, SoAintData::count, SoArealData::density, SoAintData::phase, SoArealData::radius, SoArealData::velx, SoArealData::vely, and SoArealData::velz.
Member Data Documentation
m_runtimeRealData
const runtimeRealData MFIXParticleContainer::m_runtimeRealData
Referenced by EvolveParticles(), mfix::mfix_calc_chem_txfr(), and MFIXParticleContainer().
The documentation for this class was generated from the following files:
mfix/src/des/mfix_pc.H
mfix/src/des/mfix_pc.cpp
mfix/src/des/mfix_pc_init.cpp
mfix/src/des/mfix_pc_init_collision_params.cpp
mfix/src/des/mfix_pc_remove_out_of_range.cpp
mfix/src/des/mfix_pc_replicate.cpp
mfix/src/usr/mfix_pc_usr.cpp