MFiX-Exa: mfix Class Reference
mfix Class Reference
#include <mfix.H>
Public Member Functions
mfix ()
~mfix ()
void InitParams ()
bool IsSteadyState ()
void Init (Real time)
void InitLevelData (Real time)
void init_advection ()
void mfix_init_solvers ()
void mfix_setup_solvers ()
void PostInit (Real &dt, Real time, int restart_flag, Real stop_time)
void ResizeArrays ()
void InitialRedistribution (amrex::Real l_time)
void PostProjectionRedistribution (amrex::Real l_time, amrex::Real l_dt, const amrex::Vector< amrex::MultiFab * > &a_sigma)
void PreProjectionRedistribution (amrex::Real l_time)
void PostProjectionDiagnostics (amrex::Real l_time, amrex::Vector< amrex::MultiFab * > const &epu, amrex::Vector< amrex::MultiFab * > const &vel_g_in, amrex::Vector< amrex::MultiFab * > const &p_g_in, amrex::Vector< amrex::MultiFab * > const &gp_in, amrex::Vector< amrex::MultiFab * > const &ep_g_in, amrex::Vector< amrex::MultiFab * > const &S_cc, bool proj_for_small_dt)
void WriteCheckPointFile (std::string &check_file_name, int nstep=0, Real dt=0.0, Real time=0.0)
void WritePlotFile (std::string &plot_file_name, int nstep=0, Real time=0.0)
void WriteAscentFile ()
void WriteStaticPlotFile (const std::string &plot_file_name) const
void Restart (std::string &restart_chkfile, int *nstep, Real *dt, Real *time, IntVect &Nrep)
void WriteParticleAscii (std::string &par_ascii_file_name, int nstep=0) const
void WriteAverageRegions (std::string &avg_file, int nstep, Real time=0.) const
void ComputeAverageFluidVars (const int lev, const amrex::Real time, const std::string &basename) const
void Regrid ()
void Evolve (int nstep, Real &dt, Real &prev_dt, Real time, Real stop_time)
void mfix_usr0 () const
void mfix_usr1 (Real time) const
void mfix_usr2 () const
void mfix_usr3 () const
void output (int estatus, int finish, int nstep, Real dt, Real time)
void make_mg_bc (int mg_bc[])
void make_eb_geometry ()
void make_eb_factories ()
void fill_eb_levelsets ()
void intersect_ls_walls ()
template<class F >
void build_eb_levels (EB2::GeometryShop< F > gshop)
const Geometry get_geom_ref (int lev)
std::shared_ptr< UnionListIF< EB2::PlaneIF > > get_walls (bool &has_walls)
std::shared_ptr< UnionListIF< EB2::PlaneIF > > get_real_walls (bool &has_real_walls)
std::shared_ptr< EB2::TranslationIF< EB2::PolynomialIF > > get_poly (int max_order, std::string field_prefix)
std::shared_ptr< EB2::IntersectionIF< EB2::PlaneIF, EB2::PlaneIF, EB2::PlaneIF > > make_wall (int dir, Real position, Real height, Real width)
void WriteMyEBSurface ()
void InitIOChkData ()
void ResetIOChkData ()
void InitIOPltData ()
void mfix_compute_vort ()
void mfix_compute_dt (int nstep, Real time, Real stop_time, Real &dt, Real &prev_dt)
void mfix_calc_txfr_particle (Real time, Vector< MultiFab * > const &vel_g_in, Vector< MultiFab * > const &gp_in, Vector< MultiFab * > const &T_g_in)
void mfix_add_txfr_explicit (Real dt, amrex::Vector< amrex::MultiFab * > const &vel_in, amrex::Vector< amrex::MultiFab * > const &h_g_in, amrex::Vector< amrex::MultiFab * > const &T_g_in, amrex::Vector< amrex::MultiFab const * > const &X_gk_in, amrex::Vector< amrex::MultiFab const * > const &txfr_in, amrex::Vector< amrex::MultiFab const * > const &rho_in, amrex::Vector< amrex::MultiFab const * > const &ep_g_in)
void mfix_add_txfr_implicit (amrex::Real dt, amrex::Vector< amrex::MultiFab * > const &vel_in, amrex::Vector< amrex::MultiFab * > const &h_g_in, amrex::Vector< amrex::MultiFab * > const &T_g_in, amrex::Vector< amrex::MultiFab const * > const &X_gk_in, amrex::Vector< amrex::MultiFab const * > const &txfr_in, amrex::Vector< amrex::MultiFab const * > const &rho_in, amrex::Vector< amrex::MultiFab const * > const &ep_g_in)
void mfix_correct_small_cells (Vector< MultiFab * > const &vel_in, Vector< MultiFab const * > const &ep_u_mac, Vector< MultiFab const * > const &ep_v_mac, Vector< MultiFab const * > const &ep_w_mac)
void mfix_set_velocity_bcs (Real time, Vector< MultiFab * > const &vel, int extrap_dir_bcs) const
void mfix_set_epg_bcs (const Vector< MultiFab * > &ep_g, const int dir_bc) const
void mfix_set_enthalpy_bcs (Real time, Vector< MultiFab * > const &h_g)
void mfix_set_temperature_bcs (Real time, Vector< MultiFab * > const &T_g)
void mfix_set_eb_temperature_bcs (Vector< MultiFab * > const &eb_T_g_in)
void mfix_set_density_bcs (Real time, Vector< MultiFab * > const &ro_g)
void mfix_set_tracer_bcs (Real time, Vector< MultiFab * > const &trac)
void mfix_set_species_bcs (Real time, Vector< MultiFab * > const &X_gk)
void set_velocity_bcs (Real time, const int lev, FArrayBox &vel_fab, const Box &domain, const int *extrap_dir_bcs) const
void set_epg_bcs (const int lev, FArrayBox &eps_fab, const Box &domain, const int *extrap_dir_bcs) const
void set_enthalpy_bcs (Real time, const int lev, FArrayBox &h_g_fab, const Box &domain)
void set_temperature_bcs (Real time, const int lev, FArrayBox &T_g_fab, const Box &domain)
void set_eb_temperature_bcs (const Box &sbx, const Box &bx, const Box &domain, const Real dx, const Real dy, const Real dz, const GpuArray< Real, AMREX_SPACEDIM > &plo, FArrayBox &eb_T_g_fab, const EBCellFlagFab &flags_fab)
void set_density_bcs (Real time, const int lev, FArrayBox &scal_fab, const Box &domain)
void set_tracer_bcs (Real time, const int lev, FArrayBox &trac_fab, const Box &domain)
void set_molecular_weight_bcs (Real time, const int lev, FArrayBox &scal_fab, const Box &domain)
void set_mass_fractions_g_bcs (Real time, const int lev, FArrayBox &X_gk_fab, const Box &domain)
void set_vec_bcs (const int lev, FArrayBox &vec_fab, const Box &domain) const
void set_gradp_bcs (const Box &bx, const int lev, FArrayBox &gp_fab, Box &domain)
void set_ls_inflow (const int lev, FArrayBox &ls_phi_fab, const Box &domain, const int *levelset_nghost, const int &nref, const Real *dx)
void set_temperature_bc0 (const Box &sbx, MFIter *mfi, const int lev, const Box &domain)
void set_species_bc0 (const Box &sbx, MFIter *mfi, const int lev, const Box &domain)
void set_p0 (const Box &bx, MFIter *mfi, const int lev, const Box &domain)
void set_gp0 (const int lev, const Box &domain)
template<typename F1 >
void mfix_calc_transfer_coeffs (Vector< MultiFab * > const &ep_g_in, Vector< MultiFab * > const &ro_g_in, Vector< MultiFab * > const &vel_g_in, Vector< MultiFab * > const &T_g_in, Vector< MultiFab * > const &X_gk_in, F1 DragFunc)
template<typename F1 , typename F2 >
void mfix_calc_transfer_coeffs (Vector< MultiFab * > const &ep_g_in, Vector< MultiFab * > const &ro_g_in, Vector< MultiFab * > const &vel_g_in, Vector< MultiFab * > const &T_g_in, Vector< MultiFab * > const &X_gk_in, F1 DragFunc, F2 ConvectionCoeff)
void mfix_calc_volume_fraction (Real &sum_vol)
void mfix_deposition_bcs (int lev, amrex::MultiFab &filled_mf)
void mfix_redistribute_deposition (int lev, amrex::MultiFab &mf_eps, amrex::MultiFab &mf_to_redistribute, const amrex::MultiFab *volfrac, const amrex::FabArray< EBCellFlagFab > *flags, amrex::Real max_eps)
Real volWgtSum (int lev, const MultiFab &mf, int comp, bool local=false) const
Real volEpsWgtSum (int lev, const MultiFab &mf, int comp, bool local=false) const
Real volWgtSumBox (int lev, const MultiFab &mf, int comp, const Box a_bx, bool local=false) const
void ReportGridStats () const
void mfix_set_bc_type (int lev, int nghost_bc)
void set_bcrec_lo (const int lev, const int dir, const int l_type)
void set_bcrec_hi (const int lev, const int dir, const int l_type)
void set_velocity_bc_values (amrex::Real time_in) const
void set_temperature_bc_values (amrex::Real time_in) const
void set_density_bc_values (amrex::Real time_in) const
void set_tracer_bc_values (amrex::Real time_in) const
void set_species_bc_values (amrex::Real time_in) const
void set_MAC_velocity_bcs (int lev, amrex::Vector< amrex::MultiFab const * > const &mac_rhs, amrex::Vector< amrex::MultiFab * > const &u, amrex::Vector< amrex::MultiFab * > const &v, amrex::Vector< amrex::MultiFab * > const &w, amrex::Real time)
void compute_MAC_projected_velocities (amrex::Real time, const amrex::Real l_dt, amrex::Vector< amrex::MultiFab const * > const &vel_in, amrex::Vector< amrex::MultiFab * > const &ep_u_mac, amrex::Vector< amrex::MultiFab * > const &ep_v_mac, amrex::Vector< amrex::MultiFab * > const &ep_w_mac, amrex::Vector< amrex::MultiFab const * > const &ep_g_in, amrex::Vector< amrex::MultiFab const * > const &ro_g_in, amrex::Vector< amrex::MultiFab const * > const &txfr_in, amrex::Vector< amrex::MultiFab * > const &vel_forces, amrex::Vector< amrex::MultiFab const * > const &rhs_mac)
void EvolveParcels (amrex::Real dt, amrex::Real time, amrex::RealVect &gravity, const int ls_refinement, amrex::Vector< amrex::MultiFab * > &cost, std::string &knapsack_weight_type, const int advect_enthalpy, const amrex::Real enthalpy_source)
void pic_iteration (const bool apply_forces, const bool update_parcels, const bool use_taylor_approx, const Real advance_vel_p, amrex::Real dt, amrex::RealVect &gravity, amrex::Vector< amrex::Array< amrex::MultiFab *, 3 > > &vel_s_in, amrex::Vector< amrex::MultiFab * > &ep_s_out, amrex::EBFArrayBoxFactory *ebfactory, const int ls_refinement, const MultiFab *ls_phi)
void MFIX_CalcAvgSolidsVel (Vector< Array< MultiFab *, 3 > > &vel_s, const bool do_deposition=false)
void MFIX_CalcSolidsStress (amrex::Vector< amrex::MultiFab * > &ep_s_in, amrex::RealVect &gravity_in, amrex::Vector< amrex::MultiFab * > &cost, std::string &knapsack_weight_type)
void mfix_set_pic_velocity_bcs (Vector< MultiFab * > const &vel) const
void set_pic_velocity_bcs (const int lev, FArrayBox &vel_fab, const Box &domain) const
void mfix_apply_nodal_projection (Vector< amrex::MultiFab * > &a_depdt, amrex::Real a_time, amrex::Real a_dt, amrex::Real a_prev_dt, bool proj_2, amrex::Vector< amrex::MultiFab * > const &vel_g_old_in, amrex::Vector< amrex::MultiFab * > const &vel_g_in, amrex::Vector< amrex::MultiFab * > const &p_g_in, amrex::Vector< amrex::MultiFab * > const &gp_in, amrex::Vector< amrex::MultiFab * > const &ep_g_in, amrex::Vector< amrex::MultiFab * > const &txfr_in, amrex::Vector< amrex::MultiFab const * > const &density)
void compute_tra_forces (amrex::Vector< amrex::MultiFab * > const &tra_forces, amrex::Vector< amrex::MultiFab const * > const &density)
void compute_vel_forces (amrex::Vector< amrex::MultiFab * > const &vel_forces, amrex::Vector< amrex::MultiFab const * > const &velocity, amrex::Vector< amrex::MultiFab const * > const &density, amrex::Vector< amrex::MultiFab const * > const &txfr_in, bool include_pressure_gradient=true, bool include_drag_force=false)
void compute_vel_forces_on_level (int lev, amrex::MultiFab &vel_forces, const amrex::MultiFab &velocity, const amrex::MultiFab &density, const amrex::MultiFab &txfr_in, bool include_pressure_gradient=true, bool include_drag_force=false)
void compute_laps (const bool update_lapT, const bool update_LapTrac, const bool update_LapX, amrex::Vector< amrex::MultiFab * > &lapT, amrex::Vector< amrex::MultiFab * > &lapS, amrex::Vector< amrex::MultiFab * > &lapX, amrex::Vector< amrex::MultiFab * > const &T_g_in, amrex::Vector< amrex::MultiFab * > const &trac_in, amrex::Vector< amrex::MultiFab * > const &X_gk_in, amrex::Vector< amrex::MultiFab const * > const &ep_g_in, amrex::Vector< amrex::MultiFab const * > const &ro_g_in)
void mfix_calc_chem_txfr (const Vector< MultiFab * > &chem_txfr, const Vector< MultiFab * > &ep_g_in, const Vector< MultiFab * > &ro_g_in, const Vector< MultiFab * > &vel_g_in, const Vector< MultiFab * > &p_g_in, const Vector< MultiFab * > &T_g_in, const Vector< MultiFab * > &X_gk_in, const Real time)
template<typename F1 >
void mfix_calc_chem_txfr (const Vector< MultiFab * > &chem_txfr, const Vector< MultiFab * > &ep_g_in, const Vector< MultiFab * > &ro_g_in, const Vector< MultiFab * > &vel_g_in, const Vector< MultiFab * > &p_g_in, const Vector< MultiFab * > &T_g_in, const Vector< MultiFab * > &X_gk_in, const Real time, F1 WeightFunc)
template<typename F1 , typename F2 , typename F3 >
void mfix_calc_chem_txfr (const Vector< MultiFab * > &chem_txfr, const Vector< MultiFab * > &ep_g_in, const Vector< MultiFab * > &ro_g_in, const Vector< MultiFab * > &vel_g_in, const Vector< MultiFab * > &p_g_in, const Vector< MultiFab * > &T_g_in, const Vector< MultiFab * > &X_gk_in, const Real time, F1 WeightFunc, F2 HeterogeneousRatesFunc, F3 HomogeneousRatesFunc)
void mfix_compute_convective_term (Vector< MultiFab * > &conv_u, Vector< MultiFab * > &conv_s, Vector< MultiFab * > &conv_X, Vector< MultiFab * > const &vel_forces, Vector< MultiFab * > const &tra_forces, Vector< MultiFab const * > const &vel_in, Vector< MultiFab * > const &ep_g_in, Vector< MultiFab const * > const &ro_g_in, Vector< MultiFab const * > const &h_g_in, Vector< MultiFab const * > const &trac_in, Vector< MultiFab const * > const &X_gk_in, Vector< MultiFab const * > const &txfr_in, Vector< MultiFab * > const &u_mac, Vector< MultiFab * > const &v_mac, Vector< MultiFab * > const &w_mac, Real l_dt, Real time)
void mfix_apply_predictor (Vector< MultiFab * > &conv_u_old, Vector< MultiFab * > &conv_s_old, Vector< MultiFab * > &conv_X_old, Vector< MultiFab * > &ro_RHS_old, Vector< MultiFab * > &ro_RHS, Vector< MultiFab * > &lap_trac_old, Vector< MultiFab * > &lap_trac, Vector< MultiFab * > &enthalpy_RHS_old, Vector< MultiFab * > &enthalpy_RHS, Vector< MultiFab * > &lap_T_old, Vector< MultiFab * > &lap_T, Vector< MultiFab * > &species_RHS_old, Vector< MultiFab * > &species_RHS, Vector< MultiFab * > &lap_X_old, Vector< MultiFab * > &lap_X, Vector< MultiFab * > &vel_RHS_old, Vector< Real > &rhs_pressure_g_old, Vector< Real > &rhs_pressure_g, Real time, Real dt, Real prev_dt, bool proj_2, Real &coupling_timing)
void mfix_density_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &chem_txfr)
void mfix_enthalpy_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &ep_g, Vector< MultiFab const * > const &ro_g, Vector< MultiFab * > const &X_gk, Vector< MultiFab const * > const &T_g, Vector< MultiFab const * > const &chem_txfr)
void mfix_scalar_rhs (Vector< MultiFab const * > const &trac, Vector< MultiFab const * > const &ep_g, Vector< MultiFab const * > const &ro_g, Vector< Real > const &mu_s)
void mfix_species_X_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &chem_txfr)
void mfix_momentum_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &ep_g, Vector< MultiFab const * > const &chem_txfr)
void mfix_apply_corrector (Vector< MultiFab * > &conv_u_old, Vector< MultiFab * > &conv_s_old, Vector< MultiFab * > &conv_X_old, Vector< MultiFab * > &ro_RHS_old, Vector< MultiFab * > &ro_RHS, Vector< MultiFab * > &lap_trac_old, Vector< MultiFab * > &lap_trac, Vector< MultiFab * > &enthalpy_RHS_old, Vector< MultiFab * > &enthalpy_RHS, Vector< MultiFab * > &lap_T_old, Vector< MultiFab * > &lap_T, Vector< MultiFab * > &species_RHS_old, Vector< MultiFab * > &species_RHS, Vector< MultiFab * > &lap_X_old, Vector< MultiFab * > &lap_X, Vector< MultiFab * > &vel_RHS_old, Vector< Real > &rhs_pressure_g_old, Vector< Real > &rhs_pressure_g, Real time, Real dt, Real prev_dt, bool proj_2, Real &coupling_timing)
void mfix_normalize_fluid_species (const Vector< MultiFab * > &X_gk)
void mfix_incompressible_fluid_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &ro_rhs, Vector< MultiFab const * > const &ro_g)
void mfix_idealgas_opensystem_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &lap_T, Vector< MultiFab const * > const &enthalpy_rhs, Vector< MultiFab const * > const &lap_X, Vector< MultiFab const * > const &species_rhs, Vector< MultiFab const * > const &ro_g, Vector< MultiFab const * > const &T_g, Vector< MultiFab * > const &X_gk, Vector< MultiFab const * > const &ro_rhs)
void mfix_idealgas_closedsystem_rhs (Vector< MultiFab * > const &rhs, Vector< MultiFab const * > const &lap_T, Vector< MultiFab const * > const &enthalpy_rhs, Vector< MultiFab const * > const &lap_X, Vector< MultiFab const * > const &species_rhs, Vector< MultiFab const * > const &ep_g, Vector< MultiFab const * > const &ro_g, Vector< MultiFab const * > const &T_g, Vector< MultiFab * > const &X_gk, Vector< MultiFab const * > const &ro_rhs, Vector< MultiFab const * > const &pressure_g, Vector< Real > &avgSigma, Vector< Real > &avgTheta)
void compute_convective_term (Box const &bx, int lev, const Real l_dt, MFIter const &mfi, Array4< Real > const &dvdt, Array4< Real > const &dsdt, Array4< Real > const &dXdt, const bool l_advect_density, const bool l_advect_enthalpy, const bool l_advect_tracer, const bool l_advect_species, Array4< Real const > const &vel, Array4< Real const > const &ep_g, Array4< Real const > const &rho, Array4< Real const > const &hg, Array4< Real const > const &tra, Array4< Real const > const &Xgk, const int l_nspecies, Array4< Real const > const &divu, Array4< Real const > const &ep_umac, Array4< Real const > const &ep_vmac, Array4< Real const > const &ep_wmac, Array4< Real const > const &fvel, Array4< Real const > const &ftra)
amrex::IntVect mfix_locate_max_eps (Vector< MultiFab * > &ep_s_in, const Real max_eps)
void PIC_to_PIC (const int lev, std::string &restart_file, const int pic_factor)
void PIC_to_DEM (const int lev)
Static Public Member Functions
static std::string get_load_balance_type ()
Public Attributes
FluidPhase fluid
SolidsPhase solids
Reactions reactions
Vector< Array< MultiFab *, 3 > > bcoeff
bool levelset_restart = false
int levelset_refinement = 1
int levelset_eb_refinement = 1
int levelset_pad = 2
int levelset_eb_pad = 2
bool contains_ebs = false
std::shared_ptr< DiffusionOp > diffusion_op
std::shared_ptr< Hydro::NodalProjector > nodal_projector
Static Public Attributes
static int plot_int = -1
static Real plot_per_approx = -1.
static Real plot_per_exact = -1.
static int ascent_int = -1
static Real ascent_per_approx = -1.
static int m_drag_type = DragType::Invalid
static int m_convection_type = ConvectionType::Invalid
static DepositionScheme m_deposition_scheme
static int m_constraint_type = ConstraintType::IncompressibleFluid
static int m_reaction_rates_type = ReactionRatesType::RRatesUser
static amrex::Real m_deposition_diffusion_coeff = -1.0
static amrex::Real m_deposition_scale_factor = 1.0
static amrex::Real m_max_solids_volume_fraction = 0.64356
Protected Member Functions
virtual void ErrorEst (int lev, TagBoxArray &tags, Real time, int ngrow) override
Tagging cells for refinement.
virtual void MakeNewLevelFromCoarse (int, Real, const BoxArray &, const DistributionMapping &) override
virtual void RemakeLevel (int, Real, const BoxArray &, const DistributionMapping &) override
virtual void ClearLevel (int) override
Delete level data. Called by AmrCore::regrid.
void mfix_init_fluid (int is_restarting, Real dt, Real stop_time)
void mfix_set_bc0 ()
void mfix_set_p0 ()
void mfix_set_gp0 ()
void mfix_set_ls_near_inflow ()
void mfix_project_velocity ()
void mfix_initial_iterations (Real dt, Real stop_time)
void FillPatchVel (int lev, Real time, MultiFab &mf, int icomp, int ncomp, const Vector< BCRec > &bcr)
void GetDataVel (int lev, Real time, Vector< MultiFab * > &data, Vector< Real > &datatime)
void FillPatchScalar (int lev, Real time, MultiFab &mf, ScalarToFill scalar, const Real *bc_scalar, const Vector< BCRec > &bcr)
void FillPatchSpecies (int lev, Real time, MultiFab &mf, int icomp, int ncomp, const Vector< BCRec > &bcr)
void GetDataScalar (int lev, Real time, Vector< MultiFab * > &data, ScalarToFill scalar_id, Vector< Real > &datatime)
void GetDataSpecies (int lev, Real time, Vector< MultiFab * > &data, int icomp, Vector< Real > &datatime)
void fillpatch_force (amrex::Real time, amrex::Vector< amrex::MultiFab * > const &force, int ng)
void mfix_calc_transfer_coeffs (Vector< MultiFab * > const &ep_g_in, Vector< MultiFab * > const &ro_g_in, Vector< MultiFab * > const &vel_g_in, Vector< MultiFab * > const &T_g_in, Vector< MultiFab * > const &X_gk_in)
void mfix_calc_txfr_fluid (Vector< MultiFab * > const &txfr, Vector< MultiFab * > const &ep_g_in, Vector< MultiFab * > const &ro_g_in, Vector< MultiFab * > const &vel_g_in, Vector< MultiFab * > const &T_g_in, Vector< MultiFab * > const &X_gk_in, Real time)
void AllocateArrays (int lev)
void RegridArrays (int lev)
void RegridLevelSetArray (int a_lev)
void avgDown (int crse_lev, const MultiFab &S_fine, MultiFab &S_crse)
Protected Attributes
Vector< Real > mu_s
BCList bc_list
Gpu::DeviceVector< Real > m_bc_u_g
Gpu::DeviceVector< Real > m_bc_v_g
Gpu::DeviceVector< Real > m_bc_w_g
Gpu::DeviceVector< Real > m_bc_t_g
Gpu::DeviceVector< Real > m_bc_h_g
Gpu::DeviceVector< Real > m_bc_ro_g
Gpu::DeviceVector< Real > m_bc_tracer
Gpu::HostVector< Real > m_h_bc_u_g
Gpu::HostVector< Real > m_h_bc_v_g
Gpu::HostVector< Real > m_h_bc_w_g
Gpu::HostVector< Real > m_h_bc_t_g
Gpu::HostVector< Real > m_h_bc_h_g
Gpu::HostVector< Real > m_h_bc_ro_g
Gpu::HostVector< Real > m_h_bc_tracer
Gpu::DeviceVector< Real > m_bc_ep_g
Gpu::DeviceVector< Real > m_bc_p_g
Gpu::HostVector< Real > m_h_bc_ep_g
Gpu::HostVector< Real > m_h_bc_p_g
amrex::Vector< Gpu::DeviceVector< Real > > m_bc_X_gk
Gpu::DeviceVector< Real * > m_bc_X_gk_ptr
amrex::Vector< Gpu::HostVector< Real > > m_h_bc_X_gk
Gpu::HostVector< Real * > m_h_bc_X_gk_ptr
std::map< std::string, Gpu::DeviceVector< int > > m_vel_g_bc_types
std::map< std::string, Gpu::DeviceVector< int > > m_ro_g_bc_types
std::map< std::string, Gpu::DeviceVector< int > > m_T_g_bc_types
std::map< std::string, Gpu::DeviceVector< int > > m_trac_g_bc_types
std::map< std::string, Gpu::DeviceVector< int > > m_X_gk_bc_types
Static Protected Attributes
static RealVect gp0 {0.}
static RealVect gravity {0.}
Constructor & Destructor Documentation
mfix()
mfix::mfix ()
References bc_list, m_ro_g_bc_types, m_T_g_bc_types, m_trac_g_bc_types, m_vel_g_bc_types, and m_X_gk_bc_types.
~mfix()
mfix::~mfix ()
References bcoeff.
Member Function Documentation
AllocateArrays()
void mfix::AllocateArrays (int lev) protected
avgDown()
void mfix::avgDown (int crse_lev, const MultiFab & S_fine, MultiFab & S_crse) protected
build_eb_levels()
template<class F > void mfix::build_eb_levels (EB2::GeometryShop< F > gshop) inline
Construct EB levels from Geometry shop. This builds each EB level and saves a pointer to each level into eb_levels.
References levelset_refinement.
ClearLevel()
virtual void mfix::ClearLevel (int) inline override protected virtual
Delete level data. Called by AmrCore::regrid.
compute_convective_term()
void mfix::compute_convective_term (Box const & bx, int lev, const Real l_dt, MFIter const & mfi, Array4< Real > const & dvdt, Array4< Real > const & dsdt, Array4< Real > const & dXdt, const bool l_advect_density, const bool l_advect_enthalpy, const bool l_advect_tracer, const bool l_advect_species, Array4< Real const > const & vel, Array4< Real const > const & ep_g, Array4< Real const > const & rho, Array4< Real const > const & hg, Array4< Real const > const & tra, Array4< Real const > const & Xgk, const int l_nspecies, Array4< Real const > const & divu, Array4< Real const > const & ep_umac, Array4< Real const > const & ep_vmac, Array4< Real const > const & ep_wmac, Array4< Real const > const & fvel, Array4< Real const > const & ftra)
compute_laps()
void mfix::compute_laps (const bool update_lapT, const bool update_LapTrac, const bool update_LapX, amrex::Vector< amrex::MultiFab * > & lapT, amrex::Vector< amrex::MultiFab * > & lapS, amrex::Vector< amrex::MultiFab * > & lapX, amrex::Vector< amrex::MultiFab * > const & T_g_in, amrex::Vector< amrex::MultiFab * > const & trac_in, amrex::Vector< amrex::MultiFab * > const & X_gk_in, amrex::Vector< amrex::MultiFab const * > const & ep_g_in, amrex::Vector< amrex::MultiFab const * > const & ro_g_in)
compute_MAC_projected_velocities()
void mfix::compute_MAC_projected_velocities (amrex::Real time, const amrex::Real l_dt, amrex::Vector< amrex::MultiFab const * > const & vel_in, amrex::Vector< amrex::MultiFab * > const & ep_u_mac, amrex::Vector< amrex::MultiFab * > const & ep_v_mac, amrex::Vector< amrex::MultiFab * > const & ep_w_mac, amrex::Vector< amrex::MultiFab const * > const & ep_g_in, amrex::Vector< amrex::MultiFab const * > const & ro_g_in, amrex::Vector< amrex::MultiFab const * > const & txfr_in, amrex::Vector< amrex::MultiFab * > const & vel_forces, amrex::Vector< amrex::MultiFab const * > const & rhs_mac)
compute_tra_forces()
void mfix::compute_tra_forces (amrex::Vector< amrex::MultiFab * > const & tra_forces, amrex::Vector< amrex::MultiFab const * > const & density)
compute_vel_forces()
void mfix::compute_vel_forces (amrex::Vector< amrex::MultiFab * > const & vel_forces, amrex::Vector< amrex::MultiFab const * > const & velocity, amrex::Vector< amrex::MultiFab const * > const & density, amrex::Vector< amrex::MultiFab const * > const & txfr_in, bool include_pressure_gradient = true, bool include_drag_force = false)
compute_vel_forces_on_level()
void mfix::compute_vel_forces_on_level (int lev, amrex::MultiFab & vel_forces, const amrex::MultiFab & velocity, const amrex::MultiFab & density, const amrex::MultiFab & txfr_in, bool include_pressure_gradient = true, bool include_drag_force = false)
ComputeAverageFluidVars()
void mfix::ComputeAverageFluidVars (const int lev, const amrex::Real time, const std::string & basename) const
References volWgtSumBox().
Referenced by WriteAverageRegions().
ErrorEst()
virtual void mfix::ErrorEst (int lev, TagBoxArray & tags, Real time, int ngrow) override protected virtual
Tagging cells for refinement.
Evolve()
void mfix::Evolve (int nstep, Real & dt, Real & prev_dt, Real time, Real stop_time)
Referenced by main().
EvolveParcels()
void mfix::EvolveParcels (amrex::Real dt, amrex::Real time, amrex::RealVect & gravity, const int ls_refinement, amrex::Vector< amrex::MultiFab * > & cost, std::string & knapsack_weight_type, const int advect_enthalpy, const amrex::Real enthalpy_source)
fill_eb_levelsets()
void mfix::fill_eb_levelsets ()
References contains_ebs, intersect_ls_walls(), levelset_eb_pad, levelset_eb_refinement, levelset_pad, and levelset_refinement.
Referenced by main().
fillpatch_force()
void mfix::fillpatch_force (amrex::Real time, amrex::Vector< amrex::MultiFab * > const & force, int ng) protected
FillPatchScalar()
void mfix::FillPatchScalar (int lev, Real time, MultiFab & mf, ScalarToFill scalar, const Real * bc_scalar, const Vector< BCRec > & bcr) protected
FillPatchSpecies()
void mfix::FillPatchSpecies (int lev, Real time, MultiFab & mf, int icomp, int ncomp, const Vector< BCRec > & bcr) protected
FillPatchVel()
void mfix::FillPatchVel (int lev, Real time, MultiFab & mf, int icomp, int ncomp, const Vector< BCRec > & bcr) protected
get_geom_ref()
const Geometry mfix::get_geom_ref (int lev) inline
get_load_balance_type()
static std::string mfix::get_load_balance_type () inline static
get_poly()
std::shared_ptr< EB2::TranslationIF< EB2::PolynomialIF > > mfix::get_poly (int max_order, std::string field_prefix)
get_real_walls()
std::shared_ptr< UnionListIF< EB2::PlaneIF > > mfix::get_real_walls (bool & has_real_walls)
get_walls()
std::shared_ptr< UnionListIF< EB2::PlaneIF > > mfix::get_walls (bool & has_walls)
GetDataScalar()
void mfix::GetDataScalar (int lev, Real time, Vector< MultiFab * > & data, ScalarToFill scalar_id, Vector< Real > & datatime) protected
GetDataSpecies()
void mfix::GetDataSpecies (int lev, Real time, Vector< MultiFab * > & data, int icomp, Vector< Real > & datatime) protected
GetDataVel()
void mfix::GetDataVel (int lev, Real time, Vector< MultiFab * > & data, Vector< Real > & datatime) protected
Init()
void mfix::Init (Real time)
Referenced by main().
init_advection()
void mfix::init_advection ()
Referenced by main().
InitialRedistribution()
void mfix::InitialRedistribution (amrex::Real l_time)
InitIOChkData()
void mfix::InitIOChkData ()
References ResetIOChkData().
InitIOPltData()
void mfix::InitIOPltData ()
References SoArealData::convection, AoSrealData::count, AoSintData::count, SoArealData::count, runtimeRealData::count, SoArealData::cp_s, SoArealData::density, SoArealData::dragcoeff, SoArealData::dragx, SoArealData::dragy, SoArealData::dragz, fluid, runtimeRealData::h_s_txfr, SoArealData::mass, runtimeRealData::mass_sn_txfr, SoArealData::omegax, SoArealData::omegay, SoArealData::omegaz, SoArealData::oneOverI, SoAintData::phase, SoArealData::radius, reactions, solids, SoAintData::state, SoArealData::statwt, SoArealData::temperature, runtimeRealData::vel_s_txfr, SoArealData::velx, SoArealData::vely, SoArealData::velz, SoArealData::volume, and runtimeRealData::X_sn.
InitLevelData()
void mfix::InitLevelData (Real time)
Referenced by main().
InitParams()
void mfix::InitParams ()
Referenced by main().
intersect_ls_walls()
void mfix::intersect_ls_walls ()
References levelset_eb_pad, and levelset_refinement.
Referenced by fill_eb_levelsets().
IsSteadyState()
bool mfix::IsSteadyState () inline
Referenced by main().
make_eb_factories()
void mfix::make_eb_factories ()
References levelset_eb_pad.
Referenced by main().
make_eb_geometry()
void mfix::make_eb_geometry ()
References contains_ebs, and mfix_set_bc_type().
Referenced by main().
make_mg_bc()
void mfix::make_mg_bc (int mg_bc[])
make_wall()
std::shared_ptr< EB2::IntersectionIF< EB2::PlaneIF, EB2::PlaneIF, EB2::PlaneIF > > mfix::make_wall (int dir, Real position, Real height, Real width)
MakeNewLevelFromCoarse()
virtual void mfix::MakeNewLevelFromCoarse (int , Real , const BoxArray & , const DistributionMapping &) inline override protected virtual
Make a new level using provided BoxArray and DistributionMapping and fill with interpolated coarse level data. Called by AmrCore::regrid.
mfix_add_txfr_explicit()
void mfix::mfix_add_txfr_explicit (Real dt, amrex::Vector< amrex::MultiFab * > const & vel_in, amrex::Vector< amrex::MultiFab * > const & h_g_in, amrex::Vector< amrex::MultiFab * > const & T_g_in, amrex::Vector< amrex::MultiFab const * > const & X_gk_in, amrex::Vector< amrex::MultiFab const * > const & txfr_in, amrex::Vector< amrex::MultiFab const * > const & rho_in, amrex::Vector< amrex::MultiFab const * > const & ep_g_in)
mfix_add_txfr_implicit()
void mfix::mfix_add_txfr_implicit (amrex::Real dt, amrex::Vector< amrex::MultiFab * > const & vel_in, amrex::Vector< amrex::MultiFab * > const & h_g_in, amrex::Vector< amrex::MultiFab * > const & T_g_in, amrex::Vector< amrex::MultiFab const * > const & X_gk_in, amrex::Vector< amrex::MultiFab const * > const & txfr_in, amrex::Vector< amrex::MultiFab const * > const & rho_in, amrex::Vector< amrex::MultiFab const * > const & ep_g_in)
mfix_apply_corrector()
void mfix::mfix_apply_corrector (Vector< MultiFab * > & conv_u_old, Vector< MultiFab * > & conv_s_old, Vector< MultiFab * > & conv_X_old, Vector< MultiFab * > & ro_RHS_old, Vector< MultiFab * > & ro_RHS, Vector< MultiFab * > & lap_trac_old, Vector< MultiFab * > & lap_trac, Vector< MultiFab * > & enthalpy_RHS_old, Vector< MultiFab * > & enthalpy_RHS, Vector< MultiFab * > & lap_T_old, Vector< MultiFab * > & lap_T, Vector< MultiFab * > & species_RHS_old, Vector< MultiFab * > & species_RHS, Vector< MultiFab * > & lap_X_old, Vector< MultiFab * > & lap_X, Vector< MultiFab * > & vel_RHS_old, Vector< Real > & rhs_pressure_g_old, Vector< Real > & rhs_pressure_g, Real time, Real dt, Real prev_dt, bool proj_2, Real & coupling_timing)
mfix_apply_nodal_projection()
void mfix::mfix_apply_nodal_projection (Vector< amrex::MultiFab * > & a_depdt, amrex::Real a_time, amrex::Real a_dt, amrex::Real a_prev_dt, bool proj_2, amrex::Vector< amrex::MultiFab * > const & vel_g_old_in, amrex::Vector< amrex::MultiFab * > const & vel_g_in, amrex::Vector< amrex::MultiFab * > const & p_g_in, amrex::Vector< amrex::MultiFab * > const & gp_in, amrex::Vector< amrex::MultiFab * > const & ep_g_in, amrex::Vector< amrex::MultiFab * > const & txfr_in, amrex::Vector< amrex::MultiFab const * > const & density)
mfix_apply_predictor()
void mfix::mfix_apply_predictor (Vector< MultiFab * > & conv_u_old, Vector< MultiFab * > & conv_s_old, Vector< MultiFab * > & conv_X_old, Vector< MultiFab * > & ro_RHS_old, Vector< MultiFab * > & ro_RHS, Vector< MultiFab * > & lap_trac_old, Vector< MultiFab * > & lap_trac, Vector< MultiFab * > & enthalpy_RHS_old, Vector< MultiFab * > & enthalpy_RHS, Vector< MultiFab * > & lap_T_old, Vector< MultiFab * > & lap_T, Vector< MultiFab * > & species_RHS_old, Vector< MultiFab * > & species_RHS, Vector< MultiFab * > & lap_X_old, Vector< MultiFab * > & lap_X, Vector< MultiFab * > & vel_RHS_old, Vector< Real > & rhs_pressure_g_old, Vector< Real > & rhs_pressure_g, Real time, Real dt, Real prev_dt, bool proj_2, Real & coupling_timing)
mfix_calc_chem_txfr() [1/3]
void mfix::mfix_calc_chem_txfr (const Vector< MultiFab * > & chem_txfr, const Vector< MultiFab * > & ep_g_in, const Vector< MultiFab * > & ro_g_in, const Vector< MultiFab * > & vel_g_in, const Vector< MultiFab * > & p_g_in, const Vector< MultiFab * > & T_g_in, const Vector< MultiFab * > & X_gk_in, const Real time)
References centroid, m_deposition_scheme, square_dpvm, trilinear, and true_dpvm.
Referenced by mfix_calc_chem_txfr().
mfix_calc_chem_txfr() [2/3]
template<typename F1 > void mfix::mfix_calc_chem_txfr (const Vector< MultiFab * > & chem_txfr, const Vector< MultiFab * > & ep_g_in, const Vector< MultiFab * > & ro_g_in, const Vector< MultiFab * > & vel_g_in, const Vector< MultiFab * > & p_g_in, const Vector< MultiFab * > & T_g_in, const Vector< MultiFab * > & X_gk_in, const Real time, F1 WeightFunc)
References m_reaction_rates_type, mfix_calc_chem_txfr(), and ReactionRatesType::RRatesUser.
mfix_calc_chem_txfr() [3/3]
template<typename F1 , typename F2 , typename F3 > void mfix::mfix_calc_chem_txfr (const Vector< MultiFab * > & chem_txfr, const Vector< MultiFab * > & ep_g_in, const Vector< MultiFab * > & ro_g_in, const Vector< MultiFab * > & vel_g_in, const Vector< MultiFab * > & p_g_in, const Vector< MultiFab * > & T_g_in, const Vector< MultiFab * > & X_gk_in, const Real time, F1 WeightFunc, F2 HeterogeneousRatesFunc, F3 HomogeneousRatesFunc)
References SoArealData::density, fluid, m_deposition_scale_factor, m_max_solids_volume_fraction, MFIXParticleContainer::m_runtimeRealData, mfix_deposition_bcs(), mfix_redistribute_deposition(), mfix_set_density_bcs(), mfix_set_epg_bcs(), mfix_set_species_bcs(), mfix_set_temperature_bcs(), mfix_set_velocity_bcs(), SoArealData::radius, reactions, solids, SoArealData::statwt, SoArealData::temperature, SoArealData::velx, SoArealData::vely, SoArealData::velz, and SoArealData::volume.
mfix_calc_transfer_coeffs() [1/3]
void mfix::mfix_calc_transfer_coeffs (Vector< MultiFab * > const & ep_g_in, Vector< MultiFab * > const & ro_g_in, Vector< MultiFab * > const & vel_g_in, Vector< MultiFab * > const & T_g_in, Vector< MultiFab * > const & X_gk_in) protected
References DragType::BVK2, DragType::Gidaspow, m_drag_type, mfix_calc_transfer_coeffs(), DragType::UserDrag, and DragType::WenYu.
mfix_calc_transfer_coeffs() [2/3]
template<typename F1 > void mfix::mfix_calc_transfer_coeffs (Vector< MultiFab * > const & ep_g_in, Vector< MultiFab * > const & ro_g_in, Vector< MultiFab * > const & vel_g_in, Vector< MultiFab * > const & T_g_in, Vector< MultiFab * > const & X_gk_in, F1 DragFunc)
References ConvectionType::Gunn, m_convection_type, ConvectionType::NullConvection, and ConvectionType::RanzMarshall.
Referenced by mfix_calc_transfer_coeffs(), and mfix_calc_txfr_fluid().
mfix_calc_transfer_coeffs() [3/3]
template<typename F1 , typename F2 > void mfix::mfix_calc_transfer_coeffs (Vector< MultiFab * > const & ep_g_in, Vector< MultiFab * > const & ro_g_in, Vector< MultiFab * > const & vel_g_in, Vector< MultiFab * > const & T_g_in, Vector< MultiFab * > const & X_gk_in, F1 DragFunc, F2 ConvectionCoeff)
References SoArealData::convection, dot_product(), SoArealData::dragcoeff, fluid, mfix_set_epg_bcs(), SoArealData::radius, SoArealData::statwt, SoArealData::velx, SoArealData::vely, SoArealData::velz, and SoArealData::volume.
mfix_calc_txfr_fluid()
void mfix::mfix_calc_txfr_fluid (Vector< MultiFab * > const & txfr, Vector< MultiFab * > const & ep_g_in, Vector< MultiFab * > const & ro_g_in, Vector< MultiFab * > const & vel_g_in, Vector< MultiFab * > const & T_g_in, Vector< MultiFab * > const & X_gk_in, Real time) protected
References diffusion_op, MFIXParticleContainer::InterphaseTxfrDeposition(), m_deposition_diffusion_coeff, m_max_solids_volume_fraction, mfix_calc_transfer_coeffs(), mfix_deposition_bcs(), and mfix_redistribute_deposition().
mfix_calc_txfr_particle()
void mfix::mfix_calc_txfr_particle (Real time, Vector< MultiFab * > const & vel_g_in, Vector< MultiFab * > const & gp_in, Vector< MultiFab * > const & T_g_in)
References SoArealData::convection, SoArealData::dragcoeff, SoArealData::dragx, SoArealData::dragy, SoArealData::dragz, gp0, mfix_set_temperature_bcs(), mfix_set_velocity_bcs(), set_gradp_bcs(), SoArealData::temperature, SoArealData::velx, SoArealData::vely, SoArealData::velz, and SoArealData::volume.
mfix_calc_volume_fraction()
void mfix::mfix_calc_volume_fraction (Real & sum_vol)
References diffusion_op, m_deposition_diffusion_coeff, m_max_solids_volume_fraction, mfix_deposition_bcs(), mfix_redistribute_deposition(), mfix_set_epg_bcs(), MFIXParticleContainer::SolidsVolumeDeposition(), and volWgtSum().
MFIX_CalcAvgSolidsVel()
void mfix::MFIX_CalcAvgSolidsVel (Vector< Array< MultiFab *, 3 > > & vel_s, const bool do_deposition = false)
MFIX_CalcSolidsStress()
void mfix::MFIX_CalcSolidsStress (amrex::Vector< amrex::MultiFab * > & ep_s_in, amrex::RealVect & gravity_in, amrex::Vector< amrex::MultiFab * > & cost, std::string & knapsack_weight_type)
mfix_compute_convective_term()
void mfix::mfix_compute_convective_term (Vector< MultiFab * > & conv_u, Vector< MultiFab * > & conv_s, Vector< MultiFab * > & conv_X, Vector< MultiFab * > const & vel_forces, Vector< MultiFab * > const & tra_forces, Vector< MultiFab const * > const & vel_in, Vector< MultiFab * > const & ep_g_in, Vector< MultiFab const * > const & ro_g_in, Vector< MultiFab const * > const & h_g_in, Vector< MultiFab const * > const & trac_in, Vector< MultiFab const * > const & X_gk_in, Vector< MultiFab const * > const & txfr_in, Vector< MultiFab * > const & u_mac, Vector< MultiFab * > const & v_mac, Vector< MultiFab * > const & w_mac, Real l_dt, Real time)
mfix_compute_dt()
void mfix::mfix_compute_dt (int nstep, Real time, Real stop_time, Real & dt, Real & prev_dt)
mfix_compute_vort()
void mfix::mfix_compute_vort ()
Referenced by main(), and writeNow().
mfix_correct_small_cells()
void mfix::mfix_correct_small_cells (Vector< MultiFab * > const & vel_in, Vector< MultiFab const * > const & ep_u_mac, Vector< MultiFab const * > const & ep_v_mac, Vector< MultiFab const * > const & ep_w_mac)
mfix_density_rhs()
void mfix::mfix_density_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & chem_txfr)
mfix_deposition_bcs()
void mfix::mfix_deposition_bcs (int lev, amrex::MultiFab & filled_mf)
Referenced by mfix_calc_chem_txfr(), mfix_calc_txfr_fluid(), and mfix_calc_volume_fraction().
mfix_enthalpy_rhs()
void mfix::mfix_enthalpy_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & ep_g, Vector< MultiFab const * > const & ro_g, Vector< MultiFab * > const & X_gk, Vector< MultiFab const * > const & T_g, Vector< MultiFab const * > const & chem_txfr)
mfix_idealgas_closedsystem_rhs()
void mfix::mfix_idealgas_closedsystem_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & lap_T, Vector< MultiFab const * > const & enthalpy_rhs, Vector< MultiFab const * > const & lap_X, Vector< MultiFab const * > const & species_rhs, Vector< MultiFab const * > const & ep_g, Vector< MultiFab const * > const & ro_g, Vector< MultiFab const * > const & T_g, Vector< MultiFab * > const & X_gk, Vector< MultiFab const * > const & ro_rhs, Vector< MultiFab const * > const & pressure_g, Vector< Real > & avgSigma, Vector< Real > & avgTheta)
References fluid, mfix_idealgas_opensystem_rhs(), and volWgtSumBox().
mfix_idealgas_opensystem_rhs()
void mfix::mfix_idealgas_opensystem_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & lap_T, Vector< MultiFab const * > const & enthalpy_rhs, Vector< MultiFab const * > const & lap_X, Vector< MultiFab const * > const & species_rhs, Vector< MultiFab const * > const & ro_g, Vector< MultiFab const * > const & T_g, Vector< MultiFab * > const & X_gk, Vector< MultiFab const * > const & ro_rhs)
References fluid, and mfix_incompressible_fluid_rhs().
Referenced by mfix_idealgas_closedsystem_rhs().
mfix_incompressible_fluid_rhs()
void mfix::mfix_incompressible_fluid_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & ro_rhs, Vector< MultiFab const * > const & ro_g)
Referenced by mfix_idealgas_opensystem_rhs().
mfix_init_fluid()
void mfix::mfix_init_fluid (int is_restarting, Real dt, Real stop_time) protected
mfix_init_solvers()
void mfix::mfix_init_solvers ()
Referenced by main().
mfix_initial_iterations()
void mfix::mfix_initial_iterations (Real dt, Real stop_time) protected
mfix_locate_max_eps()
amrex::IntVect mfix::mfix_locate_max_eps (Vector< MultiFab * > & ep_s_in, const Real max_eps)
mfix_momentum_rhs()
void mfix::mfix_momentum_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & ep_g, Vector< MultiFab const * > const & chem_txfr)
mfix_normalize_fluid_species()
void mfix::mfix_normalize_fluid_species (const Vector< MultiFab * > & X_gk)
mfix_project_velocity()
void mfix::mfix_project_velocity () protected
mfix_redistribute_deposition()
void mfix::mfix_redistribute_deposition (int lev, amrex::MultiFab & mf_eps, amrex::MultiFab & mf_to_redistribute, const amrex::MultiFab * volfrac, const amrex::FabArray< EBCellFlagFab > * flags, amrex::Real max_eps)
Referenced by mfix_calc_chem_txfr(), mfix_calc_txfr_fluid(), and mfix_calc_volume_fraction().
mfix_scalar_rhs()
void mfix::mfix_scalar_rhs (Vector< MultiFab const * > const & trac, Vector< MultiFab const * > const & ep_g, Vector< MultiFab const * > const & ro_g, Vector< Real > const & mu_s)
mfix_set_bc0()
void mfix::mfix_set_bc0 () protected
mfix_set_bc_type()
void mfix::mfix_set_bc_type (int lev, int nghost_bc)
Referenced by make_eb_geometry().
mfix_set_density_bcs()
void mfix::mfix_set_density_bcs (Real time, Vector< MultiFab * > const & ro_g)
Referenced by mfix_calc_chem_txfr().
mfix_set_eb_temperature_bcs()
void mfix::mfix_set_eb_temperature_bcs (Vector< MultiFab * > const & eb_T_g_in)
mfix_set_enthalpy_bcs()
void mfix::mfix_set_enthalpy_bcs (Real time, Vector< MultiFab * > const & h_g)
mfix_set_epg_bcs()
void mfix::mfix_set_epg_bcs (const Vector< MultiFab * > & ep_g, const int dir_bc) const
Referenced by mfix_calc_chem_txfr(), mfix_calc_transfer_coeffs(), and mfix_calc_volume_fraction().
mfix_set_gp0()
void mfix::mfix_set_gp0 () protected
mfix_set_ls_near_inflow()
void mfix::mfix_set_ls_near_inflow () protected
The particles see an inflow face as a solid wall; thus instead of creating a separate EBfactory for particles, we simply modify the level-set near inflow to see it as a wall
mfix_set_p0()
void mfix::mfix_set_p0 () protected
mfix_set_pic_velocity_bcs()
void mfix::mfix_set_pic_velocity_bcs (Vector< MultiFab * > const & vel) const
mfix_set_species_bcs()
void mfix::mfix_set_species_bcs (Real time, Vector< MultiFab * > const & X_gk)
Referenced by mfix_calc_chem_txfr().
mfix_set_temperature_bcs()
void mfix::mfix_set_temperature_bcs (Real time, Vector< MultiFab * > const & T_g)
Referenced by mfix_calc_chem_txfr(), and mfix_calc_txfr_particle().
mfix_set_tracer_bcs()
void mfix::mfix_set_tracer_bcs (Real time, Vector< MultiFab * > const & trac)
mfix_set_velocity_bcs()
void mfix::mfix_set_velocity_bcs (Real time, Vector< MultiFab * > const & vel, int extrap_dir_bcs) const
Referenced by mfix_calc_chem_txfr(), and mfix_calc_txfr_particle().
mfix_setup_solvers()
void mfix::mfix_setup_solvers ()
mfix_species_X_rhs()
void mfix::mfix_species_X_rhs (Vector< MultiFab * > const & rhs, Vector< MultiFab const * > const & chem_txfr)
mfix_usr0()
void mfix::mfix_usr0 () const
mfix_usr1()
void mfix::mfix_usr1 (Real time) const
Referenced by main().
mfix_usr2()
void mfix::mfix_usr2 () const
mfix_usr3()
void mfix::mfix_usr3 () const
Referenced by main().
output()
void mfix::output (int estatus, int finish, int nstep, Real dt, Real time) inline
References MFIXParticleContainer::output().
pic_iteration()
void mfix::pic_iteration (const bool apply_forces, const bool update_parcels, const bool use_taylor_approx, const Real advance_vel_p, amrex::Real dt, amrex::RealVect & gravity, amrex::Vector< amrex::Array< amrex::MultiFab *, 3 > > & vel_s_in, amrex::Vector< amrex::MultiFab * > & ep_s_out, amrex::EBFArrayBoxFactory * ebfactory, const int ls_refinement, const MultiFab * ls_phi)
PIC_to_DEM()
void mfix::PIC_to_DEM (const int lev)
References MFIXParticleContainer::get_neighbor_list(), SoArealData::mass, SoArealData::omegax, SoArealData::omegay, SoArealData::omegaz, SoArealData::oneOverI, SoArealData::radius, MFIXParticleContainer::setTotalNumParticles(), SoAintData::state, and SoArealData::statwt.
Referenced by main().
PIC_to_PIC()
void mfix::PIC_to_PIC (const int lev, std::string & restart_file, const int pic_factor)
References SoArealData::radius, restart_file, MFIXParticleContainer::setTotalNumParticles(), and SoArealData::statwt.
PostInit()
void mfix::PostInit (Real & dt, Real time, int restart_flag, Real stop_time)
Referenced by main().
PostProjectionDiagnostics()
void mfix::PostProjectionDiagnostics (amrex::Real l_time, amrex::Vector< amrex::MultiFab * > const & epu, amrex::Vector< amrex::MultiFab * > const & vel_g_in, amrex::Vector< amrex::MultiFab * > const & p_g_in, amrex::Vector< amrex::MultiFab * > const & gp_in, amrex::Vector< amrex::MultiFab * > const & ep_g_in, amrex::Vector< amrex::MultiFab * > const & S_cc, bool proj_for_small_dt)
PostProjectionRedistribution()
void mfix::PostProjectionRedistribution (amrex::Real l_time, amrex::Real l_dt, const amrex::Vector< amrex::MultiFab * > & a_sigma)
PreProjectionRedistribution()
void mfix::PreProjectionRedistribution (amrex::Real l_time)
Regrid()
void mfix::Regrid ()
Referenced by main().
RegridArrays()
void mfix::RegridArrays (int lev) protected
RegridLevelSetArray()
void mfix::RegridLevelSetArray (int a_lev) protected
RemakeLevel()
virtual void mfix::RemakeLevel (int , Real , const BoxArray & , const DistributionMapping &) inline override protected virtual
Remake an existing level using provided BoxArray and DistributionMapping and fill with existing fine and coarse data. Called by AmrCore::regrid.
ReportGridStats()
void mfix::ReportGridStats () const
Referenced by main().
ResetIOChkData()
void mfix::ResetIOChkData ()
Referenced by InitIOChkData(), and WriteCheckPointFile().
ResizeArrays()
void mfix::ResizeArrays ()
Referenced by main().
Restart()
void mfix::Restart (std::string & restart_chkfile, int * nstep, Real * dt, Real * time, IntVect & Nrep)
References restart_aux::level_prefix, and restart_file.
Referenced by main().
set_bcrec_hi()
void mfix::set_bcrec_hi (const int lev, const int dir, const int l_type)
set_bcrec_lo()
void mfix::set_bcrec_lo (const int lev, const int dir, const int l_type)
set_density_bc_values()
void mfix::set_density_bc_values (amrex::Real time_in) const
set_density_bcs()
void mfix::set_density_bcs (Real time, const int lev, FArrayBox & scal_fab, const Box & domain)
set_eb_temperature_bcs()
void mfix::set_eb_temperature_bcs (const Box & sbx, const Box & bx, const Box & domain, const Real dx, const Real dy, const Real dz, const GpuArray< Real, AMREX_SPACEDIM > & plo, FArrayBox & eb_T_g_fab, const EBCellFlagFab & flags_fab)
set_enthalpy_bcs()
void mfix::set_enthalpy_bcs (Real time, const int lev, FArrayBox & h_g_fab, const Box & domain)
set_epg_bcs()
void mfix::set_epg_bcs (const int lev, FArrayBox & eps_fab, const Box & domain, const int * extrap_dir_bcs) const
set_gp0()
void mfix::set_gp0 (const int lev, const Box & domain)
set_gradp_bcs()
void mfix::set_gradp_bcs (const Box & bx, const int lev, FArrayBox & gp_fab, Box & domain)
Referenced by mfix_calc_txfr_particle().
set_ls_inflow()
void mfix::set_ls_inflow (const int lev, FArrayBox & ls_phi_fab, const Box & domain, const int * levelset_nghost, const int & nref, const Real * dx)
set_MAC_velocity_bcs()
void mfix::set_MAC_velocity_bcs (int lev, amrex::Vector< amrex::MultiFab const * > const & mac_rhs, amrex::Vector< amrex::MultiFab * > const & u, amrex::Vector< amrex::MultiFab * > const & v, amrex::Vector< amrex::MultiFab * > const & w, amrex::Real time)
set_mass_fractions_g_bcs()
void mfix::set_mass_fractions_g_bcs (Real time, const int lev, FArrayBox & X_gk_fab, const Box & domain)
set_molecular_weight_bcs()
void mfix::set_molecular_weight_bcs (Real time, const int lev, FArrayBox & scal_fab, const Box & domain)
set_p0()
void mfix::set_p0 (const Box & bx, MFIter * mfi, const int lev, const Box & domain)
set_pic_velocity_bcs()
void mfix::set_pic_velocity_bcs (const int lev, FArrayBox & vel_fab, const Box & domain) const
set_species_bc0()
void mfix::set_species_bc0 (const Box & sbx, MFIter * mfi, const int lev, const Box & domain)
set_species_bc_values()
void mfix::set_species_bc_values (amrex::Real time_in) const
set_temperature_bc0()
void mfix::set_temperature_bc0 (const Box & sbx, MFIter * mfi, const int lev, const Box & domain)
set_temperature_bc_values()
void mfix::set_temperature_bc_values (amrex::Real time_in) const
set_temperature_bcs()
void mfix::set_temperature_bcs (Real time, const int lev, FArrayBox & T_g_fab, const Box & domain)
set_tracer_bc_values()
void mfix::set_tracer_bc_values (amrex::Real time_in) const
set_tracer_bcs()
void mfix::set_tracer_bcs (Real time, const int lev, FArrayBox & trac_fab, const Box & domain)
set_vec_bcs()
void mfix::set_vec_bcs (const int lev, FArrayBox & vec_fab, const Box & domain) const
set_velocity_bc_values()
void mfix::set_velocity_bc_values (amrex::Real time_in) const
set_velocity_bcs()
void mfix::set_velocity_bcs (Real time, const int lev, FArrayBox & vel_fab, const Box & domain, const int * extrap_dir_bcs) const
volEpsWgtSum()
Real mfix::volEpsWgtSum (int lev, const MultiFab & mf, int comp, bool local = false) const
volWgtSum()
Real mfix::volWgtSum (int lev, const MultiFab & mf, int comp, bool local = false) const
Referenced by mfix_calc_volume_fraction().
volWgtSumBox()
Real mfix::volWgtSumBox (int lev, const MultiFab & mf, int comp, const Box a_bx, bool local = false) const
Referenced by ComputeAverageFluidVars(), and mfix_idealgas_closedsystem_rhs().
WriteAscentFile()
void mfix::WriteAscentFile ()
References fluid, reactions, and solids.
Referenced by main(), and writeNow().
WriteAverageRegions()
void mfix::WriteAverageRegions (std::string & avg_file, int nstep, Real time = 0.) const
References avg_file, ComputeAverageFluidVars(), MFIXParticleContainer::ComputeAverageTemperatures(), MFIXParticleContainer::ComputeAverageVelocities(), and fluid.
Referenced by main(), and writeNow().
WriteCheckPointFile()
void mfix::WriteCheckPointFile (std::string & check_file_name, int nstep = 0, Real dt = 0.0, Real time = 0.0)
References check_file, fluid, restart_aux::level_prefix, levelset_eb_pad, levelset_eb_refinement, levelset_pad, levelset_refinement, and ResetIOChkData().
Referenced by main(), and writeNow().
WriteMyEBSurface()
void mfix::WriteMyEBSurface ()
Referenced by main().
WriteParticleAscii()
void mfix::WriteParticleAscii (std::string & par_ascii_file_name, int nstep = 0) const
References par_ascii_file.
Referenced by main(), and writeNow().
WritePlotFile()
void mfix::WritePlotFile (std::string & plot_file_name, int nstep = 0, Real time = 0.0)
References fluid, plot_file, reactions, and solids.
Referenced by main(), and writeNow().
WriteStaticPlotFile()
void mfix::WriteStaticPlotFile (const std::string & plot_file_name) const
Save variables that don't change to plot file. The idea is that they can be saved once per simulations and not repeatedly every Nth time step.
Referenced by main().
Member Data Documentation
ascent_int
int mfix::ascent_int = -1 static
Referenced by main(), and writeNow().
ascent_per_approx
Real mfix::ascent_per_approx = -1. static
Referenced by main(), and writeNow().
bc_list
BCList mfix::bc_list protected
Referenced by mfix().
bcoeff
Vector< Array<MultiFab*,3> > mfix::bcoeff
Referenced by ~mfix().
contains_ebs
bool mfix::contains_ebs = false
Referenced by fill_eb_levelsets(), and make_eb_geometry().
diffusion_op
std::shared_ptr<DiffusionOp> mfix::diffusion_op
Referenced by mfix_calc_txfr_fluid(), and mfix_calc_volume_fraction().
fluid
FluidPhase mfix::fluid
Referenced by InitIOPltData(), main(), mfix_calc_chem_txfr(), mfix_calc_transfer_coeffs(), mfix_idealgas_closedsystem_rhs(), mfix_idealgas_opensystem_rhs(), WriteAscentFile(), WriteAverageRegions(), WriteCheckPointFile(), writeNow(), and WritePlotFile().
gp0
RealVect mfix::gp0 {0.} static protected
Referenced by mfix_calc_txfr_particle().
gravity
RealVect mfix::gravity {0.} static protected
levelset_eb_pad
int mfix::levelset_eb_pad = 2
Referenced by fill_eb_levelsets(), intersect_ls_walls(), make_eb_factories(), and WriteCheckPointFile().
levelset_eb_refinement
int mfix::levelset_eb_refinement = 1
Referenced by fill_eb_levelsets(), and WriteCheckPointFile().
levelset_pad
int mfix::levelset_pad = 2
Referenced by fill_eb_levelsets(), and WriteCheckPointFile().
levelset_refinement
int mfix::levelset_refinement = 1
Parameters describing the level-set grid:
Referenced by build_eb_levels(), fill_eb_levelsets(), intersect_ls_walls(), and WriteCheckPointFile().
levelset_restart
bool mfix::levelset_restart = false
Referenced by main().
m_bc_ep_g
Gpu::DeviceVector<Real> mfix::m_bc_ep_g protected
m_bc_h_g
Gpu::DeviceVector<Real> mfix::m_bc_h_g mutable protected
m_bc_p_g
Gpu::DeviceVector<Real> mfix::m_bc_p_g protected
m_bc_ro_g
Gpu::DeviceVector<Real> mfix::m_bc_ro_g mutable protected
m_bc_t_g
Gpu::DeviceVector<Real> mfix::m_bc_t_g mutable protected
m_bc_tracer
Gpu::DeviceVector<Real> mfix::m_bc_tracer mutable protected
m_bc_u_g
Gpu::DeviceVector<Real> mfix::m_bc_u_g mutable protected
m_bc_v_g
Gpu::DeviceVector<Real> mfix::m_bc_v_g mutable protected
m_bc_w_g
Gpu::DeviceVector<Real> mfix::m_bc_w_g mutable protected
m_bc_X_gk
amrex::Vector< Gpu::DeviceVector<Real> > mfix::m_bc_X_gk mutable protected
m_bc_X_gk_ptr
Gpu::DeviceVector<Real*> mfix::m_bc_X_gk_ptr mutable protected
m_constraint_type
int mfix::m_constraint_type = ConstraintType::IncompressibleFluid static
m_convection_type
int mfix::m_convection_type = ConvectionType::Invalid static
Referenced by mfix_calc_transfer_coeffs().
m_deposition_diffusion_coeff
amrex::Real mfix::m_deposition_diffusion_coeff = -1.0 static
Referenced by mfix_calc_txfr_fluid(), and mfix_calc_volume_fraction().
m_deposition_scale_factor
amrex::Real mfix::m_deposition_scale_factor = 1.0 static
Referenced by mfix_calc_chem_txfr().
m_deposition_scheme
DepositionScheme mfix::m_deposition_scheme static
Referenced by mfix_calc_chem_txfr().
m_drag_type
int mfix::m_drag_type = DragType::Invalid static
Referenced by mfix_calc_transfer_coeffs().
m_h_bc_ep_g
Gpu::HostVector<Real> mfix::m_h_bc_ep_g protected
m_h_bc_h_g
Gpu::HostVector<Real> mfix::m_h_bc_h_g mutable protected
m_h_bc_p_g
Gpu::HostVector<Real> mfix::m_h_bc_p_g protected
m_h_bc_ro_g
Gpu::HostVector<Real> mfix::m_h_bc_ro_g mutable protected
m_h_bc_t_g
Gpu::HostVector<Real> mfix::m_h_bc_t_g mutable protected
m_h_bc_tracer
Gpu::HostVector<Real> mfix::m_h_bc_tracer mutable protected
m_h_bc_u_g
Gpu::HostVector<Real> mfix::m_h_bc_u_g mutable protected
m_h_bc_v_g
Gpu::HostVector<Real> mfix::m_h_bc_v_g mutable protected
m_h_bc_w_g
Gpu::HostVector<Real> mfix::m_h_bc_w_g mutable protected
m_h_bc_X_gk
amrex::Vector< Gpu::HostVector<Real> > mfix::m_h_bc_X_gk mutable protected
m_h_bc_X_gk_ptr
Gpu::HostVector<Real*> mfix::m_h_bc_X_gk_ptr mutable protected
m_max_solids_volume_fraction
amrex::Real mfix::m_max_solids_volume_fraction = 0.64356 static
Referenced by mfix_calc_chem_txfr(), mfix_calc_txfr_fluid(), and mfix_calc_volume_fraction().
m_reaction_rates_type
int mfix::m_reaction_rates_type = ReactionRatesType::RRatesUser static
Referenced by mfix_calc_chem_txfr().
m_ro_g_bc_types
std::map< std::string, Gpu::DeviceVector<int> > mfix::m_ro_g_bc_types protected
Referenced by mfix().
m_T_g_bc_types
std::map< std::string, Gpu::DeviceVector<int> > mfix::m_T_g_bc_types protected
Referenced by mfix().
m_trac_g_bc_types
std::map< std::string, Gpu::DeviceVector<int> > mfix::m_trac_g_bc_types protected
Referenced by mfix().
m_vel_g_bc_types
std::map< std::string, Gpu::DeviceVector<int> > mfix::m_vel_g_bc_types protected
Referenced by mfix().
m_X_gk_bc_types
std::map< std::string, Gpu::DeviceVector<int> > mfix::m_X_gk_bc_types protected
Referenced by mfix().
mu_s
Vector<Real> mfix::mu_s protected
nodal_projector
std::shared_ptr<Hydro::NodalProjector> mfix::nodal_projector
plot_int
int mfix::plot_int = -1 static
Referenced by main(), and writeNow().
plot_per_approx
Real mfix::plot_per_approx = -1. static
Referenced by main(), and writeNow().
plot_per_exact
Real mfix::plot_per_exact = -1. static
Referenced by main(), and writeNow().
reactions
Reactions mfix::reactions
Referenced by InitIOPltData(), mfix_calc_chem_txfr(), WriteAscentFile(), and WritePlotFile().
solids
SolidsPhase mfix::solids
Referenced by InitIOPltData(), mfix_calc_chem_txfr(), WriteAscentFile(), and WritePlotFile().
The documentation for this class was generated from the following files:
mfix/src/mfix.H
mfix/src/mfix.cpp
mfix/src/des/mfix_calc_chem_txfr.cpp
mfix/src/des/mfix_calc_transfer_coeffs.cpp
mfix/src/des/mfix_calc_txfr.cpp
mfix/src/des/mfix_calc_volume_fraction.cpp
mfix/src/des/mfix_set_gradp_bcs.cpp
mfix/src/eb/mfix_eb.cpp
mfix/src/eb/mfix_eb_air_reactor.cpp
mfix/src/eb/mfix_eb_box.cpp
mfix/src/eb/mfix_eb_cyclone.cpp
mfix/src/eb/mfix_eb_cylinder.cpp
mfix/src/eb/mfix_eb_general.cpp
mfix/src/eb/mfix_eb_hopper.cpp
mfix/src/eb/mfix_eb_proto_clr.cpp
mfix/src/eb/mfix_eb_regular.cpp
mfix/src/eb/mfix_get_walls.cpp
mfix/src/eb/mfix_write_eb_surface.cpp
mfix/src/io/mfix_ascent.cpp
mfix/src/io/mfix_chk.cpp
mfix/src/io/mfix_io.cpp
mfix/src/io/mfix_pic2dem.cpp
mfix/src/io/mfix_pic2pic.cpp
mfix/src/io/mfix_plt.cpp
mfix/src/io/mfix_restart.cpp
mfix/src/projection/mfix_apply_nodal_projection.cpp
mfix/src/projection/mfix_constraints.cpp
mfix/src/projection/mfix_proj_redistribution.cpp
mfix/src/usr/mfix_usr.cpp