MFiX-Exa: mfix/src/main.cpp File Reference
main.cpp File Reference
#include <fstream>
#include <iomanip>
#include <AMReX_ParmParse.H>
#include <AMReX_Geometry.H>
#include <AMReX_VisMF.H>
#include <AMReX_iMultiFab.H>
#include <AMReX_buildInfo.H>
#include <mfix.H>
#include <mfix_dem_parms.H>
#include <mfix_pic_parms.H>
#include <mfix_fluid_parms.H>
Functions
void add_par ()
void writeBuildInfo ()
void ReadParameters ()
void writeNow (int nstep, Real time, Real dt, mfix &mfix)
int main (int argc, char *argv[])
Variables
int max_step = -1
int regrid_int = -1
Real stop_time = -1.0
bool write_eb_surface = false
bool write_ls = false
std::string restart_file {""}
int repl_x = 1
int repl_y = 1
int repl_z = 1
int check_int = -1
int last_chk = -1
std::string check_file {"chk"}
std::string plot_file {"plt"}
std::string static_plt_file {"plt_ls"}
bool plotfile_on_restart = false
bool ascent_on_restart = false
int par_ascii_int = -1
int last_par_ascii = -1
std::string par_ascii_file {"par"}
int avg_int = -1
int last_avg = -1
std::string avg_file {"avg_region"}
std::string mfix_dat {"mfix.dat"}
bool stop_for_unused_inputs = false
bool checkpoint_files_output = true
Function Documentation
add_par()
void add_par ()
Referenced by main().
main()
int main (int argc, char * argv[])
References add_par(), mfix::ascent_int, ascent_on_restart, mfix::ascent_per_approx, avg_file, avg_int, check_file, check_int, checkpoint_files_output, mfix::Evolve(), mfix::fill_eb_levelsets(), mfix::fluid, mfix::Init(), mfix::init_advection(), mfix::InitLevelData(), mfix::InitParams(), mfix::IsSteadyState(), last_avg, last_chk, last_par_ascii, mfix::levelset_restart, mfix::make_eb_factories(), mfix::make_eb_geometry(), max_step, mfix::mfix_compute_vort(), mfix::mfix_init_solvers(), mfix::mfix_usr1(), mfix::mfix_usr3(), par_ascii_file, par_ascii_int, mfix::PIC_to_DEM(), plot_file, mfix::plot_int, mfix::plot_per_approx, mfix::plot_per_exact, plotfile_on_restart, mfix::PostInit(), ReadParameters(), mfix::Regrid(), regrid_int, repl_x, repl_y, repl_z, mfix::ReportGridStats(), mfix::ResizeArrays(), mfix::Restart(), restart_file, static_plt_file, stop_for_unused_inputs, stop_time, write_eb_surface, write_ls, mfix::WriteAscentFile(), mfix::WriteAverageRegions(), writeBuildInfo(), mfix::WriteCheckPointFile(), mfix::WriteMyEBSurface(), writeNow(), mfix::WriteParticleAscii(), mfix::WritePlotFile(), and mfix::WriteStaticPlotFile().
ReadParameters()
void ReadParameters ()
References ascent_on_restart, avg_file, avg_int, check_file, check_int, checkpoint_files_output, max_step, mfix_dat, par_ascii_file, par_ascii_int, plot_file, plotfile_on_restart, regrid_int, repl_x, repl_y, repl_z, restart_file, stop_for_unused_inputs, stop_time, write_eb_surface, and write_ls.
Referenced by main().
writeBuildInfo()
void writeBuildInfo ()
Referenced by main().
writeNow()
void writeNow (int nstep, Real time, Real dt, mfix & mfix)
References mfix::ascent_int, mfix::ascent_per_approx, avg_file, avg_int, check_file, check_int, checkpoint_files_output, mfix::fluid, last_avg, last_chk, last_par_ascii, mfix::mfix_compute_vort(), par_ascii_file, par_ascii_int, plot_file, mfix::plot_int, mfix::plot_per_approx, mfix::plot_per_exact, mfix::WriteAscentFile(), mfix::WriteAverageRegions(), mfix::WriteCheckPointFile(), mfix::WriteParticleAscii(), and mfix::WritePlotFile().
Referenced by main().
Variable Documentation
ascent_on_restart
bool ascent_on_restart = false
Referenced by main(), and ReadParameters().
avg_file
std::string avg_file {"avg_region"}
Referenced by main(), ReadParameters(), mfix::WriteAverageRegions(), and writeNow().
avg_int
int avg_int = -1
Referenced by main(), ReadParameters(), and writeNow().
check_file
std::string check_file {"chk"}
Referenced by main(), ReadParameters(), mfix::WriteCheckPointFile(), and writeNow().
check_int
int check_int = -1
Referenced by main(), ReadParameters(), and writeNow().
checkpoint_files_output
bool checkpoint_files_output = true
Referenced by main(), ReadParameters(), and writeNow().
last_avg
int last_avg = -1
Referenced by main(), and writeNow().
last_chk
int last_chk = -1
Referenced by main(), and writeNow().
last_par_ascii
int last_par_ascii = -1
Referenced by main(), and writeNow().
max_step
int max_step = -1
Referenced by main(), and ReadParameters().
mfix_dat
std::string mfix_dat {"mfix.dat"}
Referenced by ReadParameters().
par_ascii_file
std::string par_ascii_file {"par"}
Referenced by main(), ReadParameters(), writeNow(), and mfix::WriteParticleAscii().
par_ascii_int
int par_ascii_int = -1
Referenced by main(), ReadParameters(), and writeNow().
plot_file
std::string plot_file {"plt"}
Referenced by main(), ReadParameters(), writeNow(), and mfix::WritePlotFile().
plotfile_on_restart
bool plotfile_on_restart = false
Referenced by main(), and ReadParameters().
regrid_int
int regrid_int = -1
Referenced by main(), and ReadParameters().
repl_x
int repl_x = 1
Referenced by main(), and ReadParameters().
repl_y
int repl_y = 1
Referenced by main(), and ReadParameters().
repl_z
int repl_z = 1
Referenced by main(), and ReadParameters().
restart_file
std::string restart_file {""}
Referenced by main(), mfix::PIC_to_PIC(), ReadParameters(), and mfix::Restart().
static_plt_file
std::string static_plt_file {"plt_ls"}
Referenced by main().
stop_for_unused_inputs
bool stop_for_unused_inputs = false
Referenced by main(), and ReadParameters().
stop_time
Real stop_time = -1.0
Referenced by main(), and ReadParameters().
write_eb_surface
bool write_eb_surface = false
Referenced by main(), and ReadParameters().
write_ls
bool write_ls = false
Referenced by main(), and ReadParameters().