MFiX-Exa: mfix/src/des/mfix_des_K.H File Reference
mfix_des_K.H File Reference
#include "mfix_pc.H"
Functions
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cross_product (const amrex::RealVect &a, const amrex::RealVect &b, amrex::RealVect &c)
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real dot_product (const amrex::RealVect &a, const amrex::RealVect &b)
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cfrelvel (const amrex::RealVect &vel1, const amrex::RealVect &vel2, const amrex::Real &radius1, const amrex::Real &radius2, const amrex::RealVect &omega1, const amrex::RealVect &omega2, amrex::Real &vrn, amrex::RealVect &vslip, const amrex::RealVect &normal, const amrex::Real dist_mag)
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real interp_level_set (const amrex::RealVect &pos, const int n_refine, amrex::Array4< amrex::Real const > const &phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &dxi)
AMREX_GPU_HOST_DEVICE AMREX_INLINE void level_set_normal (const amrex::RealVect &pos, const int n_refine, amrex::RealVect &normal, amrex::Array4< amrex::Real const > const &phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &dxi)
Function Documentation
cfrelvel()
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cfrelvel (const amrex::RealVect & vel1, const amrex::RealVect & vel2, const amrex::Real & radius1, const amrex::Real & radius2, const amrex::RealVect & omega1, const amrex::RealVect & omega2, amrex::Real & vrn, amrex::RealVect & vslip, const amrex::RealVect & normal, const amrex::Real dist_mag)
References cross_product(), and dot_product().
Referenced by MFIXParticleContainer::EvolveParticles().
cross_product()
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cross_product (const amrex::RealVect & a, const amrex::RealVect & b, amrex::RealVect & c)
Referenced by cfrelvel(), and MFIXParticleContainer::EvolveParticles().
dot_product()
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real dot_product (const amrex::RealVect & a, const amrex::RealVect & b)
Referenced by cfrelvel(), MFIXParticleContainer::EvolveParticles(), level_set_normal(), and mfix::mfix_calc_transfer_coeffs().
interp_level_set()
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real interp_level_set (const amrex::RealVect & pos, const int n_refine, amrex::Array4< amrex::Real const > const & phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & dxi)
Referenced by MFIXParticleContainer::EvolveParticles(), and MFIXParticleContainer::RemoveOutOfRange().
level_set_normal()
AMREX_GPU_HOST_DEVICE AMREX_INLINE void level_set_normal (const amrex::RealVect & pos, const int n_refine, amrex::RealVect & normal, amrex::Array4< amrex::Real const > const & phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & dxi)
References dot_product().
Referenced by MFIXParticleContainer::EvolveParticles().